apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:gofjwobsKWBdNyMVlwuQ1RypNgPi/uRYQPiafb7DF2soZO9WiP8XDw==,iv:indXzZEpBcqHCOWTgvD7qqSNvBBV/4pjf9Fa/667Fj4=,tag:jsw4njjj5eo28yH+SYk8UQ==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYmpqWDE0T3JjUkY0NWRS
        M1pTa0pLOXJYelJnOEZmNWJRQjNlUS9NczFNCmNXUDI3MWxhMm40WVptWXZndWhz
        OTArdit1NWZvL1ZqUTlGdlJMZjBHL2MKLS0tIDZJY2x0OSt0dHMyVFVLenF3bGlz
        NHNHMG9IaWxOdkRXTVF5djNZVDFOVVUKIoSt31bTp4ppTb1nMsLs5ZBkIZTO00hM
        1Dpw7gR9AzN9dA5BJZ7KSX1uUozUfn1JwHEGoNPOhDRVIZoyJYaFxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T22:55:59Z"
  mac: ENC[AES256_GCM,data:Jg2gHX2Z3G7pIIi2ad2TmZoKGX6AYLf+vSSpuWNY86VXtHLP7vQciaNmMTA5WW+o90jnyfPEubC2Jm/Xyun9jeGriabJpG/s/VU9610UBFOqYPwqT36mErRvevYJwNOJY1LwbLueoWmx7VZYESM0S1kMIp6BaTzJUrB7vv8dIkc=,iv:doArBgqKduoV0+aHRBVsgjYm0g5SsQ2KhWuWL/wnQSU=,tag:O2bAyE0V+UFHRCnB05DGTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
