apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:kMXytPwnoDsCLI4gMxrMOFQyiNJzOIAGQW1B1O07XOHmYO6GJifDuw==,iv:W7bvthek7wotJkBW+jgjUKOX+DWrtMFmQKjxgNTwndg=,tag:HknecMCBY+fzYlz31LaEtQ==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQTFQdzhYbGdZWTZwaE1M
        dGVBdW1DMUlBdUNpSFRJYm1sTDVuOVlMUlVRCnp6L1d4NEdTOEdQcGRIM1R1T0lm
        VXFkOXloM3NXOUE1OHhLN3ExYzhnWncKLS0tIGNNaC9PdUV5V1NubXpHcFpmdzRm
        RHh1R1lUMHdIZVZveHpPbEsyY0Rpb1EKSb7ZGJT+E84u9NZNJ8KNiRrh/Q1pnoUA
        Po3jVnTC/tPhiuT85xteimp1mRiAmoL7B6yYb+vovThNO6+GO96nDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T19:52:36Z"
  mac: ENC[AES256_GCM,data:akWX+2zCk9cooFXXUtK+gj5HWuv+8VWYIloGl0IzCDkw4H1DkmZLj95OFUUboQ+0sV43BYhJlU3aOmehPJrVUujCR5RQEC9H6vJnbERzIMNAGaIOQtBcVHXHpQmuUkGhef3gedwQDNVQ6nOAkGuZc6KfcajJAbLu6mX42z97r1c=,iv:21QnJq4IcRQstySfPiEoUSnCQBJtqYroKhms8yPQwFs=,tag:Uy931A7G5xLxh5fe6SgaiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
