apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:2Jspc+1QvEBehKih,iv:v8IqI9/U3ZcHIpmobEj4gctEEa6KEq4I2kaE5UwmTWI=,tag:Rji1VCeo61/Jdh43MCpT9A==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNVhnTVBzMGtXdUJCTWx3
        NEluVDVSTDVUNytSc0htTEJ3ZDRCN1BML1dNClpKRElBcmJzVzhuYlVXNkZxQ2l5
        R2NxczhJbTlTYlNwbUNXbG5NQll3WGcKLS0tIGpRMnZwLzZlODl0UVVoZnVXWHlJ
        Ti9aMndLMERCUXlTYk5mM2kySmoyWnMKobEjHlrvIJQDhpYq4jev8sN6HutaQS9G
        yq4RpOmQsfVgSCR/da9UWFOL8Etyz6GKAngnhnXoKpUOX2teNcklGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T19:52:37Z"
  mac: ENC[AES256_GCM,data:r0BmBexiMKUUBvsNGSJXxZ4v3SKD0Hg5bhvFIIBHplJzPWH47YSD6cVvkJfGwQrAts+I+cNPEn528haAs4iKCdWUr53gQ1I9cRCa2jM70xo4yIg3LfBVYbt0vuO4utELv0va3eztRGnPt0a0qPd0dqdcsbYWp+4a2xYmcE0B/wY=,iv:m2BqPaW7aVuQ/zYMHZC63nssSc2r5LM6NuBxNTdNPgQ=,tag:TEdHqdb7cq+DWjzv61YeUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
