apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:nPNu7zAe0aXZruN6,iv:rV4KUQegGddvR/oiQzlMNFRiUNwjtXTOvFszQmJXC8s=,tag:LyUQC0mTSiWTyvOfp69AbQ==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaXFrZnQ3ZXA2ZlBzQTI5
        dXVIaVd4ZVUyaDBSeStERTZ4YjltUmNVcEhZCmtuVWRpc2hvYmhIUnExdnZYZXVF
        Mm1YNmw3NlluZS9PcEtCUmdYOHVieHcKLS0tIFBxelRTbGQrWERJd2N0SHRMZCtL
        REFWZnF2REJrdWxCanBmc3ozU05CaTAKX+MUcv0zaOIUMC3yXi3gU5BKAkfAA90y
        7LtCCLzOCCJhluBFnExbanFHbWxQNeHbbj2qo1eO3iHvkB/MrXLrgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T22:55:59Z"
  mac: ENC[AES256_GCM,data:cCaDY25ORJuz7X+6cVuHFjiva7Sf9LKs7XiYuRn/kLQQFavokP9lPvfABLcw+/OKHs+14B4+LMEZbSaLmhFjqHRzoykp9wc8qH3DoJB0frmtffuwxkDlteEqqSEQleEMCvinQ1nRsVPpfM+111Byhl+GlRwYFHSgnH/23p5iigM=,iv:byxqqZZDxaCJLMJkLkb7eVTmUMiKYtsZtTzvbPKL2OA=,tag:vYNHvwamfgg1wDhdKYgXLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
