apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:jgvyiuetWBEHikCh3uDqadkBMs53EQefA/k61YhXSsw=,iv:FAzlGNQ7Nfp025QS4oq+xaukiwcKQxuYtkwIbEl7BZA=,tag:eD9AC09ulU5+NkF4VsaqWA==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aE13YVJEdEwvdWR0MENy
        Q1FhN1QxdmliMStleDE2OGpGR25qaU02RGhFClMvT0t0NjhVcUN6UkRFUElza2RT
        cHVjbVhPM1A5bmNBZ214ZUFJSXM0U1EKLS0tIGErYStJK0xJU0RSTzR6QTdYdWw5
        Smlkc3JKT1pLc1AwbExudTJiM0F2VWMKbDtCDUBBe1DuoM29wtZWIH3p26v8lH/m
        g8Tv/gMlU4GY/YQUARWZzYeKUlyPKS+jHjk+W58HD+6BHKJ11BqKhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T22:55:59Z"
  mac: ENC[AES256_GCM,data:uXXfvD9hyV/AEEM+5IEkoJjVwO2yqnF/etRlZE5r+spTKJr3LD3d7HrDQ+nXQXGeW2SiUCRlU2aoDuzdjwEEz1whs9ZpnqZpqZ4ISn3wN43m+2QgohTftmIzNkhDvqhYeDiMG34181M6puL/o9eTe2tUK8iany7MmZ+lLcwfa1M=,iv:qwqx/gicunbt4sDWI8B2lqz8TjxSsh31TkQrrk0s5B8=,tag:ZMpma5P4kCdCsmm8qkEaAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
