apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:S2n6m3lnwItGvUHRvLoaLvy1e8lmwCw8wLhybpVQRU4=,iv:ksc2eI0PxWld7+BKhvrya/wMwc0J6yne0h6zYZEQ2Ds=,tag:nGyZhjSenuCmYnQSWsIiWw==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL1VCNnlrMTJXOVdBaFh6
        dlNXU3JuUlpGNU1BT00zalRnQ2xYRW9nL0NnCk9mZWdCcC9wZURXdnlWOW1SR1JI
        WGZWeXV5YlkzWExTdWg4WEpGRERPSm8KLS0tIHBEbjErdnRaY3RJMlh3dHBrWFQr
        dTIxWWRzVmMzZkl5dlI1UFpDd2ZtaHMKZ27NMBsrJ9HvtjROKyxBbyxOjB9YtWzS
        Rw3Fx+2NVyVtPglV3b3ML6iJfSUUuMqY1tdhCJ3z3jrzjQ0JXAXxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T19:52:36Z"
  mac: ENC[AES256_GCM,data:wznfpxvUef9QBY8oOhqTiXP0IpV/yiFZrOdMBZgcOIBDuHNRC6TvPY92wJfOGcJGAcscKLlz2XbJjrwdhFAAIi3yrhjMjxuSiz1NUfKbSQr2EKjouSFCUhL0eK5JKpNdjBSnedQ85FSbdtiOvbLMRokfsJURAUfC2l9eb48d52o=,iv:hTb1h/MRoLnY1VtN9+whAkNySDGzR6PQypcbk8IdofA=,tag:3TQ+EyvZ56AtiVTOrQeojQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
