apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1zGUUI6WtbSy8/gkFbkbjwDy7wE4PKueKxl9xjThyfTSaHRPeLqCTHA4SlsCBalZipkPM0MUuyqN/81xLlxiLg+eDMk1FHxE9yAaYPMazubjy1ODw+YgJTP86tFpYmdpPcMMPc9m8u5Ovznqjl7WXuUkhjOAVvFD59AT0t5/J0uaXusjP81/fVN77BakYAb6Xdp9MGvWHLOH1anuWyCEQY7HNXOcNL8GLp7ihxuQnjziHj+v,iv:0OCP+oevK2HulA0QVRTvT9bFa1k2pselY0vkFKFpMbU=,tag:N1FkZV2S1Bqvvn7g+zgZhg==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWVVGcmN3U2hMWXQvMTlX
        T1I4TmNud1NGSXc4WVRzSi9YQmtOZm5IZEdNCndWU3VYNTIvUHVSSWpUa1M5Y2hQ
        Szhncms4b0xmeHpXS29lS25VRFFlbkUKLS0tIDdrU1BWS2o5azdWQldyNHM5aXFo
        bDR4RlRkYjhSYkQrL0pqN1pISlFVQTQKmLKEUfEgfLOqJgubQ1NpCOjPYsXGFyU2
        TfSsgvT8qqEA/mWyKVC1GjykwS0WYz3c9MprP8Fa9BfWGbGfNt7qhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T19:52:36Z"
  mac: ENC[AES256_GCM,data:TlUSmKG02C458wJ3yYe51NqN62FMEJ3v0IeAxfsCeOQpQTEt5AMi+lnDTFhJLd7F3F1SH6+T2lTpLgq3nP/XtcvpDoYrzToYFUVUjyrdo0zmp0IrSsiP+FzOKpNSpTOYfejRgMFnL1U0lpBX0ei+9onfcbGOwFlgTenBtOpygpM=,iv:/jUJy01hwT8Kw4BC/eZKkbXkLOGwNxpkCmgCrKjttkI=,tag:HHlrRNtP16P+MKrg8z3t5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
