apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:hw7j5G4xcnM6LQZWFsNH+r3cPyEAlrH281WIoGdD2XsLY4kuG7wMdOmwQrjLqog4w+NvHrR32iry8Np0Ws8ByX8GTt/IAPl/BFNZ5dAeMkijJ3Jl3zKb7cmBG1X8Buf2qjrG+M/61AMsqUX63m26VlU/Foc2LkBJUDU4WZ4S5LpqsENVgvgL/GGh8aPiIusP/04NIELaSwM5Ec3OxlDDjw3g/YcR7dtmkeHfJ6+1NeuxE3Rt,iv:GPeQgDI3/1AnnaQt96k5FU1Jp+iCb7TL2o50Lzx2TuA=,tag:fLD37rDspsrflL500p6dKg==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWb3BJRVk4dTkzRUhPaGpu
        c0dPZmpwTjZLZjE5MGZQaUppcTdaQnNGa0dJCjJ2Q2NMVTArTFdRYlJSZEQxSXVL
        OHpQM0hjODlZdklvamtQSFJvYmRWRWMKLS0tIE10cDRVV0c0RkU3Kzh3K3h2OVpU
        OW9USEkxODM1STF1eTFpbHpFT1pkM1UKboYPF0EBcIsKQU7+oI3QxU/kchGFTvNl
        lCRUIo/Yqd9V5JODsy6fAEfj7xIE5WpE7oc1yqBarBWqx575lOjELQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T22:55:59Z"
  mac: ENC[AES256_GCM,data:91P/BlOKOcCWsjyvKPnMBCSLzF/0MrC71Fwa3+22o3ZRBLAXxAaO5Ja6PrRZiywcu5ymbg27UUxmWG2btBwL1Rqrn/Ig/cNHw1v0Gsz88UMPEeZhBMXZg/y5eBXSZx6iOupjYIybWfPWGUUwL/vy3m6WHWm9tAaku+iyNhz9BgA=,iv:S1swkS1xvjk9hiOUjz+6xMSgd1uXyZzZBLdXC8AqOkA=,tag:W+6igAjkBg5cANOnLDYgcg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
