apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:+yXRNw8TKm9rmtWmjp9Kjn61HHF0F4x+VAYA/7qmQI+fBCHAVlAvRA==,iv:h9Yh7+pfWsGY7mYd1w31WZcxg+A2kA6Meb0TvQGE0hI=,tag:xQd1fN0w+zwHTR6wR8t9IA==,type:str]
sops:
  age:
    - recipient: age1qn3t6h86a72zkjna0zc4823ra5270vf579ljetcs0gpdw8p9duesd7pwhs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVmREL05qQWdmUGwvV2J3
        bjhGdXJxcjBvQms4elR2L2VtRFNsMC9oZGhRCml3bGdSc2VxenI0NndWSnB3YmpR
        ZzR3OXhJclpENjl1b0UvbzFESXRkekEKLS0tIDBoNjRGMXZoa3FuZDRYWVVmZ2h2
        TmZvWG1OUng2TVNSSng5Qll1S1FGamsK1R1PiHtFXwcAh21YHJWaot7j67w7PByn
        lp/RvCZeXkWs3pItNZ/DMSc0j1fg+sZUSQ3ugtvonq7Ua4f9o30g9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T22:55:59Z"
  mac: ENC[AES256_GCM,data:Kb4zutUCnhK/kElvqkpk0DGHRb9pHaW5f3lj3RCwZnydQbhmTvRpKiMjB231+MPVC4Jq9/9F0Bv6oU5nBRKAfrWYOK7vMGff5byBU2vyrVJ2scNKAk9TI6f9KvNUB1KQKLFVAgJhMuIB4EBT1zg6578WWj1tA5lmikEvXbanPrc=,iv:M07didX9AUIJ8WqixM3Tm2gLB/9REoqhh+/5uhHdjLQ=,tag:+rwgGB6VuI8WHeZpCw36gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
